sandbox/dan: updated the configure and makefiles
git-svn-id: file:///home/jtrmal/Downloads/kaldi-git-conversion/kaldi-svn/sandbox/dan@2799 5e6a8d80-dfce-4ca6-a32a-6e07a63d50c8

diff --git a/src/configure b/src/configure
--- a/src/configure
+++ b/src/configure
@@ -10,12 +10,17 @@
 
 #  Example command lines:
 # ./configure
+# ./configure --shared  ## shared libraries.
 # ./configure --mkl-root=/opt/intel/mkl 
 # ./configure --mkl-root=/opt/intel/mkl --threaded-math=yes
 # ./configure  --openblas-root=../tools/OpenBLAS/install  # before doing
 #        # this, cd to ../tools and type "make openblas".  Note:
 #        # this is not working correctly on all platforms, do "make test"
 #        # and look out for segmentation faults.
+
+#This should be incremented after every significant change of the configure script
+#I.e. after each change that affects the kaldi.mk or the build system as whole
+CONFIGURE_VERSION=2
 
 function rel2abs {
   if [ ! -z "$1" ]; then
@@ -27,6 +32,7 @@ function rel2abs {
 function read_dirname {
   local dir_name=`expr "X$1" : '[^=]*=\(.*\)'`;
   local retval=`rel2abs $dir_name`
+  [ -z $retval ] && echo "Bad option '$1': no such directory" && exit 1;
   echo $retval
 }
 
@@ -60,21 +66,37 @@ unset OPENBLASROOT
 unset MKLLIBDIR
 
 function usage {
-  echo 'Usage: ./configure [--threaded-atlas={yes|no}] [--atlas-root=ATLASROOT] [--fst-root=FSTROOT] 
+  echo 'Usage: ./configure [--static|--shared] [--threaded-atlas={yes|no}] [--atlas-root=ATLASROOT] [--fst-root=FSTROOT] 
   [--openblas-root=OPENBLASROOOT] [--clapack-root=CLAPACKROOT] [--mkl-root=MKLROOT] [--mkl-libdir=MKLLIBDIR]
-  [--omp-libdir=OMPDIR]  [--static-math={yes|no}] [--threaded-math={yes|no}] [--mathlib=ATLAS|MKL|CLAPACK|OPENBLAS] 
+  [--omp-libdir=OMPDIR] [--static-fst={yes|no}] [--static-math={yes|no}] [--threaded-math={yes|no}] [--mathlib=ATLAS|MKL|CLAPACK|OPENBLAS] 
   [--use-cuda={yes|no}] [--cudatk-dir=CUDATKDIR]';
 }
 
 threaded_atlas=false #  By default, use the un-threaded version of ATLAS.
 threaded_math=${threaded_atlas}
 static_math=false
+static_fst=false
 use_cuda=true
+dynamic_kaldi=false
+
+cmd_line="$0 $@"  # Save the command line to include in kaldi.mk
 
 while [ $# -gt 0 ];
 do
   case "$1" in
   --help) usage; exit 0 ;;
+  --version) echo $CONFIGURE_VERSION; exit 0 ;;
+  --static)
+    # FIXME depends on order of options first--static/--shared then --static-math -> it will override it
+  dynamic_kaldi=false; 
+  static_math=true;
+  static_fst=true;
+  shift ;;  
+  --shared)
+  dynamic_kaldi=true; 
+  static_math=false;
+  static_fst=false;
+  shift ;;  
   --atlas-root=*) 
   ATLASROOT=`read_dirname $1`; shift ;;
   --threaded-atlas=yes)
@@ -93,6 +115,10 @@ do
   static_math=true; shift ;;
   --static-math=no)
   static_math=false; shift ;;
+  --static-fst=yes)
+  static_fst=true; shift ;;
+  --static-fst=no)
+  static_fst=false; shift ;;
   --fst-root=*)
   FSTROOT=`read_dirname $1`; shift ;;
   --clapack-root=*)
@@ -106,7 +132,7 @@ do
   --omp-libdir=*)
   OMPLIBDIR=`read_dirname $1`; shift ;;
   --mathlib=*)
-  MATHLIB=`read_dirname $1`; shift ;;
+  MATHLIB=`expr "X$1" : '[^=]*=\(.*\)'`; shift ;;
   --cudatk-dir=*)
   CUDATKDIR=`read_dirname $1`; shift ;; #CUDA is used in src/cudamatrix and src/nnet{,bin} only
   *)  echo "Unknown argument: $1, exiting"; usage; exit 1 ;;
@@ -116,7 +142,7 @@ done
 
 
 function failure {
-  echo "***configure failed: $* ***"
+  echo "***configure failed: $* ***" >&2
   if [ -f kaldi.mk ]; then rm kaldi.mk; fi
   exit 1;
 } 
@@ -329,10 +355,24 @@ function linux_configure_debian_ubuntu {
   echo ATLASINC = $ATLASROOT/include >> kaldi.mk
   echo ATLASLIBS = $ATLASLIBS >> kaldi.mk
   cat makefiles/linux_atlas.mk >> kaldi.mk
-  echo "Successfully configured for Debian/Ubuntu Linux [static libraries] with ATLASLIBS =$ATLASLIBS"
+  echo "Successfully configured for Debian/Ubuntu Linux [dynamic libraries] with ATLASLIBS =$ATLASLIBS"
   $use_cuda && linux_configure_cuda
   exit 0;
 }
+
+function linux_configure_debian7 {
+  ATLASLIBS="/usr/lib/atlas-base/libatlas.so.3.0 /usr/lib/atlas-base/libf77blas.so.3.0 /usr/lib/atlas-base/libcblas.so.3 /usr/lib/atlas-base/liblapack_atlas.so.3"
+  for f in $ATLASLIBS; do 
+    [ ! -f $f ] && return 1;
+  done
+  echo ATLASINC = $ATLASROOT/include >> kaldi.mk
+  echo ATLASLIBS = $ATLASLIBS >> kaldi.mk
+  cat makefiles/linux_atlas.mk >> kaldi.mk
+  echo "Successfully configured for Debian 7 [dynamic libraries] with ATLASLIBS =$ATLASLIBS"
+  $use_cuda && linux_configure_cuda
+  exit 0;
+}
+
 
 function linux_configure_static {
   if $threaded_atlas; then pt=pt; else pt=""; fi
@@ -343,7 +383,7 @@ function linux_configure_static {
      linux_check_static &&  ATLASLIBDIR=$dir
     done
     if [ -z $ATLASLIBDIR ]; then # Note: it'll pick up the last one below.
-      echo "Could not find libatlas.a in any of the obvious places... will try dynamic libraries."
+      echo "Could not find libatlas.a in any of the generic-Linux places, but we'll try other stuff..."
       return 1;
     fi
   elif [ ! -f $ATLASLIBDIR/libatlas.a ]; then
@@ -409,7 +449,7 @@ function linux_configure_dynamic {
        linux_check_dynamic && ATLASLIBDIR=$dir
     done
     if [ -z $ATLASLIBDIR ]; then
-      echo "Could not find libatlas.so in any of the obvious places."
+      echo "Could not find libatlas.so in any of the obvious places, will most likely try static:"
       return 1;
     fi
   elif [ ! -f $ATLASLIBDIR/libatlas.so ]; then
@@ -477,7 +517,14 @@ if [ -f kaldi.mk ]; then
   cp kaldi.mk kaldi.mk.bak
 fi
 
-cp makefiles/common.mk kaldi.mk
+printf "# This file was generated using the following command:\n# $cmd_line\n\n" > kaldi.mk
+cat makefiles/common.mk >> kaldi.mk
+if $dynamic_kaldi ; then
+KALDILIBDIR=`pwd`/lib
+echo "KALDI_FLAVOR := dynamic" >> kaldi.mk
+echo "KALDILIBDIR := $KALDILIBDIR" >> kaldi.mk
+fi
+echo "CONFIGURE_VERSION := $CONFIGURE_VERSION" >> kaldi.mk
 
 # Most of the OS-specific steps below will append to kaldi.mk
 echo "Doing OS specific configurations ..."
@@ -497,16 +544,16 @@ if [ "`uname`" == "Darwin"  ]; then
   # posix_memalign and gcc -rdynamic options not present on OS X 10.5.*
   osx_ver=`sw_vers | grep ProductVersion | awk '{print $2}' | sed -e 's?\.[^.]*$??'`
   echo "Configuring for OS X version $osx_ver ..."
-  if [ $osx_ver == "10.5" ]; then
+  if [ "$osx_ver" == "10.5" ]; then
     check_exists makefiles/darwin_10_5.mk
     cat makefiles/darwin_10_5.mk >> kaldi.mk 
-  elif [ $osx_ver == "10.6" ]; then
+  elif [ "$osx_ver" == "10.6" ]; then
     check_exists makefiles/darwin_10_6.mk
     cat makefiles/darwin_10_6.mk >> kaldi.mk 
-  elif [ $osx_ver == "10.7" ]; then
+  elif [ "$osx_ver" == "10.7" ]; then
     check_exists makefiles/darwin_10_7.mk
     cat makefiles/darwin_10_7.mk >> kaldi.mk 
-  elif [ $osx_ver == "10.8" ]; then
+  elif [ "$osx_ver" == "10.8" ]; then
     check_exists makefiles/darwin_10_8.mk
     cat makefiles/darwin_10_8.mk >> kaldi.mk 
   else 
@@ -531,13 +578,23 @@ if [ "`uname -o`" == "Cygwin"  ]; then
 fi
 
 if [ "`uname`" == "Linux" ]; then
-  if [ ! -f $FSTROOT/lib/libfst.a ]; then
-    failure "Static OpenFST library not found:  See ../tools/INSTALL"
+  if  $static_fst ; then
+      OPENFSTLIBS="$FSTROOT/lib/libfst.a"
+      fst_type='a'
+  else
+      OPENFSTLIBS="-L${FSTROOT}/lib -lfst"
+      OPENFSTLDFLAGS="-Wl,-rpath=${FSTROOT}/lib"
+      fst_type='so'
   fi
+  if [ ! -f "$FSTROOT/lib/libfst.${fst_type}" ]; then
+    failure "Static=[$static_fst] OpenFST library not found:  See ../tools/INSTALL"
+  fi
+  echo OPENFSTLIBS = $OPENFSTLIBS >> kaldi.mk
+  echo OPENFSTLDFLAGS = $OPENFSTLDFLAGS >> kaldi.mk
   echo FSTROOT = $FSTROOT >> kaldi.mk
 
   echo "On Linux: Checking for linear algebra header files ..."
-  if [ $MATHLIB == "ATLAS" ]; then
+  if [ "$MATHLIB" == "ATLAS" ]; then
     if [ ! -f $ATLASROOT/include/cblas.h ] || [ ! -f $ATLASROOT/include/clapack.h ] ; then
       failure "Could not find required header files cblas.h or clapack.h in ATLAS dir '$ATLASROOT/include'"
     fi
@@ -554,19 +611,31 @@ if [ "`uname`" == "Linux" ]; then
     # containing {liblapack.a,libblas.a}, and linking against just these two 
     # libraries worked.  
 
-    linux_configure_static || \
+    if $static_math; then
+      # Prefer static to dynamic math.
+      linux_configure_static || \
+        linux_configure_dynamic || \
+        linux_configure_debian_ubuntu 64 || \
+        linux_configure_debian_ubuntu || \
+        linux_configure_debian7 || \
+        linux_atlas_failure "Failed to configure ATLAS lbiraries";
+    else
+      # Prefer dynamic to static math.
       linux_configure_dynamic || \
-      linux_configure_debian_ubuntu 64 || \
-      linux_configure_debian_ubuntu || \
-      linux_atlas_failure "Failed to configure ATLAS lbiraries";
+        linux_configure_static || \
+        linux_configure_debian_ubuntu 64 || \
+        linux_configure_debian_ubuntu || \
+        linux_configure_debian7 || \
+        linux_atlas_failure "Failed to configure ATLAS lbiraries";
+    fi
 
-  elif [ $MATHLIB == "MKL" ]; then
+  elif [ "$MATHLIB" == "MKL" ]; then
     if [ "`uname -m`" != "x86_64" ]; then
       failure "MKL on Linux only supported for Intel(R) 64 architecture (x86_64). 
       See makefiles/linux_64_mkl.mk to manually configure for other platforms."
     fi
     
-    if  is_set $MKLROOT -a ! is_set $MKLLIBDIR; then
+    if  is_set "$MKLROOT" -a ! is_set "$MKLLIBDIR"; then
       echo -n "Configuring MKL library directory: "
       MKLLIBDIR=`linux_configure_mkllibdir $MKLROOT`
       if [ $? -ne 0 ]; then
@@ -576,17 +645,17 @@ if [ "`uname`" == "Linux" ]; then
       fi
     fi
 
-    MKL_LINK_LINE=`linux_configure_mkl_libraries "$MKLLIBDIR" $static_math $threaded_math`
+    MKL_LINK_LINE=`linux_configure_mkl_libraries "$MKLLIBDIR" $static_math $threaded_math` || exit 1
 
-    MKL_COMPILE_LINE=`linux_configure_mkl_includes "$MKLROOT" "$MKLLIBDIR"`
+    MKL_COMPILE_LINE=`linux_configure_mkl_includes "$MKLROOT" "$MKLLIBDIR"` || exit 1
     echo "MKL include directory configured as: $MKL_COMPILE_LINE"
     MKL_COMPILE_LINE=" -I${MKL_COMPILE_LINE} "
     
     if ! is_set $OMPLIBDIR ; then
       if  $static_math ; then
-        OMPLIBDIR=`linux_configure_omplibdir "$MKLROOT" "$MKLLIBDIR" "a"` 
+        OMPLIBDIR=`linux_configure_omplibdir "$MKLROOT" "$MKLLIBDIR" "a"`
       else
-        OMPLIBDIR=`linux_configure_omplibdir "$MKLROOT" "$MKLLIBDIR" "so"` 
+        OMPLIBDIR=`linux_configure_omplibdir "$MKLROOT" "$MKLLIBDIR" "so"`
       fi
     fi
     check_library $OMPLIBDIR "libiomp5" "a" || check_library $OMPLIBDIR "libiomp5" "so" \
@@ -620,14 +689,14 @@ if [ "`uname`" == "Linux" ]; then
     echo "Successfully configured for Linux with MKL libs from $MKLROOT"
     exit 0;
 
-  elif [ $MATHLIB == "CLAPACK" ]; then
-    if [ -z $CLAPACKROOT ]; then
+  elif [ "$MATHLIB" == "CLAPACK" ]; then
+    if [ -z "$CLAPACKROOT" ]; then
       failure "Must specify the location of CLAPACK with --clapack-root option (and it must exist)"
     fi
     if [ ! -f ../tools/CLAPACK/clapack.h ]; then
       failure could not find file ../tools/CLAPACK/clapack.h
     fi
-    if [ ! -d $CLAPACKROOT ]; then
+    if [ ! -d "$CLAPACKROOT" ]; then
       failure "The directory $CLAPACKROOT does not exist"
     fi
     # Also check for cblas.h and f2c.h
@@ -640,9 +709,9 @@ if [ "`uname`" == "Linux" ]; then
     $use_cuda && linux_configure_cuda
     echo "Successfully configured for Linux with CLAPACK libs from $CLAPACKROOT"
     exit 0
-  elif [ $MATHLIB == "OPENBLAS" ]; then
-    OPENBLASROOT=`rel2abs $OPENBLASROOT`
-    if [ -z $OPENBLASROOT ]; then
+  elif [ "$MATHLIB" == "OPENBLAS" ]; then
+    OPENBLASROOT=`rel2abs "$OPENBLASROOT"`
+    if [ -z "$OPENBLASROOT" ]; then
       failure "Must specify the location of OPENBLAS with --openblas-root option (and it must exist)"
     fi
     if [ ! -f $OPENBLASROOT/lib/libopenblas.so ]; then 
