sandbox/idlak: merged trunk/src till r2692 to idlak/src
git-svn-id: file:///home/jtrmal/Downloads/kaldi-git-conversion/kaldi-svn/sandbox/idlak@2696 5e6a8d80-dfce-4ca6-a32a-6e07a63d50c8

diff --git a/src/configure b/src/configure
--- a/src/configure
+++ b/src/configure
@@ -10,12 +10,17 @@
 
 #  Example command lines:
 # ./configure
+# ./configure --shared  ## shared libraries.
 # ./configure --mkl-root=/opt/intel/mkl 
 # ./configure --mkl-root=/opt/intel/mkl --threaded-math=yes
 # ./configure  --openblas-root=../tools/OpenBLAS/install  # before doing
 #        # this, cd to ../tools and type "make openblas".  Note:
 #        # this is not working correctly on all platforms, do "make test"
 #        # and look out for segmentation faults.
+
+#This should be incremented after every significant change of the configure script
+#I.e. after each change that affects the kaldi.mk or the build system as whole
+CONFIGURE_VERSION=2
 
 function rel2abs {
   if [ ! -z "$1" ]; then
@@ -27,6 +32,7 @@ function rel2abs {
 function read_dirname {
   local dir_name=`expr "X$1" : '[^=]*=\(.*\)'`;
   local retval=`rel2abs $dir_name`
+  [ -z $retval ] && echo "Bad option '$1': no such directory" && exit 1;
   echo $retval
 }
 
@@ -66,23 +72,38 @@ unset OPENBLASROOT
 unset MKLLIBDIR
 
 function usage {
-  echo 'Usage: ./configure [--threaded-atlas={yes|no}] [--atlas-root=ATLASROOT] [--fst-root=FSTROOT] 
+  echo 'Usage: ./configure [--static|--shared] [--threaded-atlas={yes|no}] [--atlas-root=ATLASROOT] [--fst-root=FSTROOT] 
   [--openblas-root=OPENBLASROOOT] [--clapack-root=CLAPACKROOT] [--mkl-root=MKLROOT] [--mkl-libdir=MKLLIBDIR]
-  [--omp-libdir=OMPDIR]  [--static-math={yes|no}] [--threaded-math={yes|no}] [--mathlib=ATLAS|MKL|CLAPACK|OPENBLAS] 
+  [--omp-libdir=OMPDIR] [--static-fst={yes|no}] [--static-math={yes|no}] [--threaded-math={yes|no}] [--mathlib=ATLAS|MKL|CLAPACK|OPENBLAS] 
   [--use-cuda={yes|no}] [--cudatk-dir=CUDATKDIR] [--idlak={yes|no}]';
 }
 
 threaded_atlas=false #  By default, use the un-threaded version of ATLAS.
 threaded_math=${threaded_atlas}
 static_math=false
+static_fst=false
 use_cuda=true
-##set to false to ignore idlak system
-idlak=true
+dynamic_kaldi=false
+idlak=true  # set to false to ignore idlak system
+
+cmd_line="$0 $@"  # Save the command line to include in kaldi.mk
 
 while [ $# -gt 0 ];
 do
   case "$1" in
   --help) usage; exit 0 ;;
+  --version) echo $CONFIGURE_VERSION; exit 0 ;;
+  --static)
+    # FIXME depends on order of options first--static/--shared then --static-math -> it will override it
+  dynamic_kaldi=false; 
+  static_math=true;
+  static_fst=true;
+  shift ;;  
+  --shared)
+  dynamic_kaldi=true; 
+  static_math=false;
+  static_fst=false;
+  shift ;;  
   --atlas-root=*) 
   ATLASROOT=`read_dirname $1`; shift ;;
   --threaded-atlas=yes)
@@ -101,6 +122,10 @@ do
   static_math=true; shift ;;
   --static-math=no)
   static_math=false; shift ;;
+  --static-fst=yes)
+  static_fst=true; shift ;;
+  --static-fst=no)
+  static_fst=false; shift ;;
   --fst-root=*)
   FSTROOT=`read_dirname $1`; shift ;;
   --clapack-root=*)
@@ -355,7 +380,7 @@ function linux_configure_static {
      linux_check_static &&  ATLASLIBDIR=$dir
     done
     if [ -z $ATLASLIBDIR ]; then # Note: it'll pick up the last one below.
-      echo "Could not find libatlas.a in any of the obvious places... will try dynamic libraries."
+      echo "Could not find libatlas.a in any of the generic-Linux places, but we'll try other stuff..."
       return 1;
     fi
   elif [ ! -f $ATLASLIBDIR/libatlas.a ]; then
@@ -421,7 +446,7 @@ function linux_configure_dynamic {
        linux_check_dynamic && ATLASLIBDIR=$dir
     done
     if [ -z $ATLASLIBDIR ]; then
-      echo "Could not find libatlas.so in any of the obvious places."
+      echo "Could not find libatlas.so in any of the obvious places, will most likely try static:"
       return 1;
     fi
   elif [ ! -f $ATLASLIBDIR/libatlas.so ]; then
@@ -508,7 +533,16 @@ if [ -f kaldi.mk ]; then
   cp kaldi.mk kaldi.mk.bak
 fi
 
-cp makefiles/common.mk kaldi.mk
+printf "# This file was generated using the following command:\n# $cmd_line\n\n" > kaldi.mk
+#echo "# $cmd_line" >> kaldi.mk
+#echo >> kaldi.mk
+cat makefiles/common.mk >> kaldi.mk
+if $dynamic_kaldi ; then
+KALDILIBDIR=`pwd`/lib
+echo "KALDI_FLAVOR := dynamic" >> kaldi.mk
+echo "KALDILIBDIR := $KALDILIBDIR" >> kaldi.mk
+fi
+echo "CONFIGURE_VERSION := $CONFIGURE_VERSION" >> kaldi.mk
 
 # Most of the OS-specific steps below will append to kaldi.mk
 echo "Doing OS specific configurations ..."
@@ -570,9 +604,19 @@ if [ "`uname -o`" == "Cygwin"  ]; then
 fi
 
 if [ "`uname`" == "Linux" ]; then
-  if [ ! -f $FSTROOT/lib/libfst.a ]; then
-    failure "Static OpenFST library not found:  See ../tools/INSTALL"
+  if  $static_fst ; then
+      OPENFSTLIBS="$FSTROOT/lib/libfst.a"
+      fst_type='a'
+  else
+      OPENFSTLIBS="-L${FSTROOT}/lib -lfst"
+      OPENFSTLDFLAGS="-Wl,-rpath=${FSTROOT}/lib"
+      fst_type='so'
   fi
+  if [ ! -f "$FSTROOT/lib/libfst.${fst_type}" ]; then
+    failure "Static=[$static_fst] OpenFST library not found:  See ../tools/INSTALL"
+  fi
+  echo OPENFSTLIBS = $OPENFSTLIBS >> kaldi.mk
+  echo OPENFSTLDFLAGS = $OPENFSTLDFLAGS >> kaldi.mk
   echo FSTROOT = $FSTROOT >> kaldi.mk
 
   if $idlak; then
@@ -603,11 +647,21 @@ if [ "`uname`" == "Linux" ]; then
     # containing {liblapack.a,libblas.a}, and linking against just these two 
     # libraries worked.  
 
-    linux_configure_static || \
+    if $static_math; then
+      # Prefer static to dynamic math.
+      linux_configure_static || \
+        linux_configure_dynamic || \
+        linux_configure_debian_ubuntu 64 || \
+        linux_configure_debian_ubuntu || \
+        linux_atlas_failure "Failed to configure ATLAS lbiraries";
+    else
+      # Prefer dynamic to static math.
       linux_configure_dynamic || \
-      linux_configure_debian_ubuntu 64 || \
-      linux_configure_debian_ubuntu || \
-      linux_atlas_failure "Failed to configure ATLAS lbiraries";
+        linux_configure_static || \
+        linux_configure_debian_ubuntu 64 || \
+        linux_configure_debian_ubuntu || \
+        linux_atlas_failure "Failed to configure ATLAS lbiraries";
+    fi
 
   elif [ "$MATHLIB" == "MKL" ]; then
     if [ "`uname -m`" != "x86_64" ]; then
