sandbox/dan updated tools/Makefile and src/configure to trunk version
git-svn-id: file:///home/jtrmal/Downloads/kaldi-git-conversion/kaldi-svn/sandbox/dan@2811 5e6a8d80-dfce-4ca6-a32a-6e07a63d50c8

diff --git a/src/configure b/src/configure
--- a/src/configure
+++ b/src/configure
@@ -79,6 +79,8 @@ static_fst=false
 use_cuda=true
 dynamic_kaldi=false
 
+cmd_line="$0 $@"  # Save the command line to include in kaldi.mk
+
 while [ $# -gt 0 ];
 do
   case "$1" in
@@ -140,7 +142,7 @@ done
 
 
 function failure {
-  echo "***configure failed: $* ***"
+  echo "***configure failed: $* ***" >&2
   if [ -f kaldi.mk ]; then rm kaldi.mk; fi
   exit 1;
 } 
@@ -245,7 +247,7 @@ function linux_configure_omplibdir {
     echo "Testing $libext from [$libexts] " >&2
 
     check_library $mkllibdir "libiomp5" $libext \
-	&& echo `readlink -f $mkllibdir` && return
+    && echo `readlink -f $mkllibdir` && return
     
     local testdir=`(cd $mklroot; cd ..; cd lib/intel64;pwd)` 
     test -d $testdir && check_library $testdir "libiomp5" $libext && echo `readlink -f $testdir` && return;
@@ -353,10 +355,24 @@ function linux_configure_debian_ubuntu {
   echo ATLASINC = $ATLASROOT/include >> kaldi.mk
   echo ATLASLIBS = $ATLASLIBS >> kaldi.mk
   cat makefiles/linux_atlas.mk >> kaldi.mk
-  echo "Successfully configured for Debian/Ubuntu Linux [static libraries] with ATLASLIBS =$ATLASLIBS"
+  echo "Successfully configured for Debian/Ubuntu Linux [dynamic libraries] with ATLASLIBS =$ATLASLIBS"
   $use_cuda && linux_configure_cuda
   exit 0;
 }
+
+function linux_configure_debian7 {
+  ATLASLIBS="/usr/lib/atlas-base/libatlas.so.3.0 /usr/lib/atlas-base/libf77blas.so.3.0 /usr/lib/atlas-base/libcblas.so.3 /usr/lib/atlas-base/liblapack_atlas.so.3"
+  for f in $ATLASLIBS; do 
+    [ ! -f $f ] && return 1;
+  done
+  echo ATLASINC = $ATLASROOT/include >> kaldi.mk
+  echo ATLASLIBS = $ATLASLIBS >> kaldi.mk
+  cat makefiles/linux_atlas.mk >> kaldi.mk
+  echo "Successfully configured for Debian 7 [dynamic libraries] with ATLASLIBS =$ATLASLIBS"
+  $use_cuda && linux_configure_cuda
+  exit 0;
+}
+
 
 function linux_configure_static {
   if $threaded_atlas; then pt=pt; else pt=""; fi
@@ -501,7 +517,8 @@ if [ -f kaldi.mk ]; then
   cp kaldi.mk kaldi.mk.bak
 fi
 
-cp makefiles/common.mk kaldi.mk
+printf "# This file was generated using the following command:\n# $cmd_line\n\n" > kaldi.mk
+cat makefiles/common.mk >> kaldi.mk
 if $dynamic_kaldi ; then
 KALDILIBDIR=`pwd`/lib
 echo "KALDI_FLAVOR := dynamic" >> kaldi.mk
@@ -585,20 +602,32 @@ if [ "`uname`" == "Linux" ]; then
     
     # Finding out where the libraries are located: 
     # First we look for the static libraries and then look for dynamic ones.
-    # We're looking for four libraries, all in the same directory, named 
-    # libcblas.a, libatlas.a, libf77blas.a, and a library that's variously 
-    # named liblapack.a, libclapack.a, or liblapack_atlas.a, but which exports 
-    # the symbol ATL_cgetrf. 
-    # Note: there is a different type of ATLAS installation that is not 
-    # covered.  We saw a case where there was a directory called /usr/lib/atlas 
-    # containing {liblapack.a,libblas.a}, and linking against just these two 
-    # libraries worked.  
+    # We're looking for four libraries, all in the same directory, named
+    # libcblas.a, libatlas.a, libf77blas.a, and a library that's variously
+    # named liblapack.a, libclapack.a, or liblapack_atlas.a, but which exports
+    # the symbol ATL_cgetrf.
+    # Note: there is a different type of ATLAS installation that is not
+    # covered.  We saw a case where there was a directory called /usr/lib/atlas
+    # containing {liblapack.a,libblas.a}, and linking against just these two
+    # libraries worked.
 
-    linux_configure_static || \
+    if $static_math; then
+      # Prefer static to dynamic math.
+      linux_configure_static || \
+        linux_configure_dynamic || \
+        linux_configure_debian_ubuntu 64 || \
+        linux_configure_debian_ubuntu || \
+        linux_configure_debian7 || \
+        linux_atlas_failure "Failed to configure ATLAS lbiraries";
+    else
+      # Prefer dynamic to static math.
       linux_configure_dynamic || \
-      linux_configure_debian_ubuntu 64 || \
-      linux_configure_debian_ubuntu || \
-      linux_atlas_failure "Failed to configure ATLAS lbiraries";
+        linux_configure_static || \
+        linux_configure_debian_ubuntu 64 || \
+        linux_configure_debian_ubuntu || \
+        linux_configure_debian7 || \
+        linux_atlas_failure "Failed to configure ATLAS lbiraries";
+    fi
 
   elif [ "$MATHLIB" == "MKL" ]; then
     if [ "`uname -m`" != "x86_64" ]; then
@@ -616,17 +645,17 @@ if [ "`uname`" == "Linux" ]; then
       fi
     fi
 
-    MKL_LINK_LINE=`linux_configure_mkl_libraries "$MKLLIBDIR" $static_math $threaded_math`
+    MKL_LINK_LINE=`linux_configure_mkl_libraries "$MKLLIBDIR" $static_math $threaded_math` || exit 1
 
-    MKL_COMPILE_LINE=`linux_configure_mkl_includes "$MKLROOT" "$MKLLIBDIR"`
+    MKL_COMPILE_LINE=`linux_configure_mkl_includes "$MKLROOT" "$MKLLIBDIR"` || exit 1
     echo "MKL include directory configured as: $MKL_COMPILE_LINE"
     MKL_COMPILE_LINE=" -I${MKL_COMPILE_LINE} "
     
     if ! is_set $OMPLIBDIR ; then
       if  $static_math ; then
-        OMPLIBDIR=`linux_configure_omplibdir "$MKLROOT" "$MKLLIBDIR" "a"` 
+        OMPLIBDIR=`linux_configure_omplibdir "$MKLROOT" "$MKLLIBDIR" "a"`
       else
-        OMPLIBDIR=`linux_configure_omplibdir "$MKLROOT" "$MKLLIBDIR" "so"` 
+        OMPLIBDIR=`linux_configure_omplibdir "$MKLROOT" "$MKLLIBDIR" "so"`
       fi
     fi
     check_library $OMPLIBDIR "libiomp5" "a" || check_library $OMPLIBDIR "libiomp5" "so" \
@@ -699,7 +728,9 @@ if [ "`uname`" == "Linux" ]; then
     fi
     echo "OPENBLASLIBS = $OPENBLASLIBS" >> kaldi.mk
     echo "OPENBLASROOT = $OPENBLASROOT" >> kaldi.mk
-    echo "Successfully configured."
+    echo "Warning (OPENBLAS): this part of the configure process is not properly tested and will not work."
+    $use_cuda && linux_configure_cuda
+    echo "Successfully configured OpenBLAS from $OPENBLASROOT."
     exit 0;
   else 
     failure "Unsupported linear algebra library '$MATHLIB'"
